services:
  postgres:
    image: postgres:16
    container_name: tmapp-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tmapp_user -d tmapp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: